version: "3"

services:
  nas-tools:
    image: jxxghp/nas-tools:latest
    #ports:
      #- 3000:3000        # 默认的webui控制端口
    volumes:
      - ./nastools/config:/config   # 冒号左边请修改为你想保存配置的路径
      - ./share/media:/media   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment: 
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
     #- REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
    restart: always
    #network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - ./qbit/config:/config
      - ./share/media:/downloads
    ports:
      #- 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ./jackett/config:/config
      - ./share/media:/downloads
    #ports:
      #- 9117:9117
    restart: unless-stopped
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./jellyfin/config:/config
      #- ./jellyfin/cache:/cache
      - ./share/media:/data/media
    #ports:
      #- 8096:8096
      #- 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    
networks:
  default:
    external:
      name: nastools.io
